# Generated by Django 4.2 on 2024-12-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='top_activities/')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToursAndActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
                ('passengers_count', models.PositiveIntegerField(default=1)),
                ('duration', models.CharField(blank=True, choices=[('1 hr', '1 hr'), ('2 hr', '2 hr'), ('3 hr', '3 hr'), ('4 hr', '4 hr'), ('5 hr', '5 hr'), ('6 hr', '6 hr'), ('half day', 'Half Day'), ('full day', 'Full Day'), ('2 day', '2 Day')], max_length=30, null=True)),
                ('category', models.CharField(blank=True, choices=[('Food & Drink', 'Food & Drink'), ('Sport', 'Sport'), ('City Tour', 'City Tour'), ('Shopping', 'Shopping'), ('Adventure', 'Adventure'), ('Art', 'Art'), ('Culture', 'Culture'), ('Art Culture', 'Art Culture'), ('Adventure Nature', 'Adventure Nature')], max_length=30, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('media_gallery', models.ManyToManyField(blank=True, related_name='tours', to='ToursAndActivities.tourimage')),
            ],
        ),
    ]
