# Generated by Django 4.2 on 2024-11-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursAndActivities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toursandactivities',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='toursandactivities',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='toursandactivities',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='toursandactivities',
            name='start_date',
        ),
    ]
