# Generated by Django 4.2 on 2024-11-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursAndActivities', '0003_toursandactivities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursandactivities',
            name='category',
            field=models.CharField(blank=True, choices=[('Food & Drink', 'Food & Drink'), ('Sport', 'Sport'), ('City Tour', 'City Tour'), ('Shopping', 'Shopping'), ('Adventure', 'Adventure'), ('Art', 'Art'), ('Culture', 'Culture'), ('Art Culture', 'Art Culture'), ('Adventure Nature', 'Adventure Nature')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='toursandactivities',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 hr', '1 hr'), ('2 hr', '2 hr'), ('3 hr', '3 hr'), ('4 hr', '4 hr'), ('5 hr', '5 hr'), ('6 hr', '6 hr'), ('half day', 'Half Day'), ('full day', 'Full Day'), ('2 day', '2 Day')], max_length=30, null=True),
        ),
    ]
