# Generated by Django 4.2 on 2024-10-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=10),
        ),
    ]
