# Generated by Django 4.2 on 2024-10-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver_feedback/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
