# Generated by Django 4.2 on 2024-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driverfeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
