# Generated by Django 4.2 on 2024-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('noted', 'Noted')], default='pending', max_length=20),
        ),
    ]
