# Generated by Django 4.2 on 2024-10-23 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin__isnull', True), ('customer__isnull', False)), models.Q(('admin__isnull', False), ('customer__isnull', True)), _connector='OR'), name='either_customer_or_admin'),
        ),
    ]
