# Generated by Django 4.2 on 2024-12-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('flight', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True)),
                ('currency', models.CharField(blank=True, choices=[('QAR', 'QAR'), ('Pound', 'Pound'), ('USD', 'USD'), ('EUR', 'EURO')], default='QAR', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourBookingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('posted', 'Posted'), ('ongoing', 'OnGoing'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('flight', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True)),
                ('currency', models.CharField(blank=True, choices=[('QAR', 'QAR'), ('Pound', 'Pound'), ('USD', 'USD'), ('EUR', 'EURO')], default='QAR', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferBookingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transfer_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transferbooking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
