# Generated by Django 4.2 on 2024-10-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbooking',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
