# Generated by Django 4.2 on 2024-12-28 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToursAndActivities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbookingaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='transfer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transfermeetassist'),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='travel_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourbookingaudit',
            name='tour_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tourbooking'),
        ),
        migrations.AddField(
            model_name='tourbookingaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToursAndActivities.toursandactivities'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='travel_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='booking.hotelcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='transferbookingaudit',
            unique_together={('transfer_booking', 'action', 'field_name', 'old_value', 'new_value')},
        ),
        migrations.AlterUniqueTogether(
            name='tourbookingaudit',
            unique_together={('tour_booking', 'action', 'field_name', 'old_value', 'new_value')},
        ),
    ]
