# Generated by Django 4.2 on 2024-10-16 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ToursAndActivities', '0001_initial'),
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='transfer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transfermeetassist'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToursAndActivities.toursandactivities'),
        ),
    ]
