# Generated by Django 4.2 on 2024-10-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursAndActivities', '0001_initial'),
        ('booking', '0002_transferbooking_from_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='TourBooking',
        ),
    ]
