# Generated by Django 4.2 on 2024-10-12 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_rename_booking_tourbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
