# Generated by Django 4.2 on 2024-10-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_transferbooking_unique_code'),
    ]

    operations = [
    ]
