# Generated by Django 4.2 on 2024-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_transferbooking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
