# Generated by Django 4.2 on 2024-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_transferbooking_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
