# Generated by Django 4.2 on 2024-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_tourbooking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbooking',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
