# Generated by Django 4.2 on 2024-10-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_transferbooking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferbooking',
            old_name='price',
            new_name='amount',
        ),
    ]
