# Generated by Django 4.2 on 2024-10-26 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0012_tourbooking_amount_tourbooking_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
