# Generated by Django 4.2 on 2024-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_tourbooking_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
