# Generated by Django 4.2 on 2024-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_transferbookingaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('posted', 'Posted'), ('ongoing', 'OnGoing'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
