# Generated by Django 4.2 on 2024-11-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_hotelcategory_hotelsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='tour_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
