# Generated by Django 4.2 on 2024-11-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_tourbookingaudit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbookingaudit',
            old_name='transfer_booking',
            new_name='tour_booking',
        ),
    ]
