# Generated by Django 4.2 on 2024-11-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_transfer_booking_tourbookingaudit_tour_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
