# Generated by Django 4.2 on 2024-11-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_transferbookingaudit_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourbookingaudit',
            unique_together={('tour_booking', 'action', 'field_name', 'old_value', 'new_value')},
        ),
    ]
