# Generated by Django 4.2 on 2024-11-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_tourbookingaudit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
