# Generated by Django 4.2 on 2024-11-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_tourbooking_currency_tourbooking_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='currency',
            field=models.CharField(blank=True, choices=[('QAR', 'QAR'), ('GBP', 'Pound'), ('USD', 'USD'), ('EUR', 'EURO')], default='QAR', max_length=20, null=True),
        ),
    ]
