# Generated by Django 4.2 on 2024-11-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_alter_transferbooking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='amount',
            field=models.CharField(blank=True, null=True),
        ),
    ]
