# Generated by Django 4.2 on 2024-11-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_transferbooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='amount',
            field=models.CharField(blank=True, default='0', null=True),
        ),
    ]
