# Generated by Django 4.2 on 2024-11-09 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_transferbooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='amount',
            field=models.CharField(blank=True, default='0', null=True, validators=[django.core.validators.RegexValidator('^\\d*\\.?\\d*$', 'Only numeric characters are allowed.')]),
        ),
    ]
