# Generated by Django 4.2 on 2024-11-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_transferbooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
