# Generated by Django 4.2 on 2024-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_transferbooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
