# Generated by Django 4.2 on 2024-11-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_alter_transferbooking_amount'),
    ]

    operations = [
    ]
