# Generated by Django 4.2 on 2024-11-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20241109_1302'),
    ]

    operations = [
    ]
