# Generated by Django 4.2 on 2024-11-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_alter_transferbooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='currency',
            field=models.CharField(blank=True, choices=[('QAR', 'QAR'), ('GBP', 'Pound'), ('USD', 'USD'), ('EUR', 'EURO')], default='QAR', max_length=20, null=True),
        ),
    ]
