# Generated by Django 4.2 on 2024-11-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_alter_tourbooking_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
