# Generated by Django 4.2 on 2024-11-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_tourbooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='currency',
            field=models.CharField(blank=True, choices=[('QAR', 'QAR'), ('Pound', 'Pound'), ('USD', 'USD'), ('EUR', 'EURO')], default='QAR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='currency',
            field=models.CharField(blank=True, choices=[('QAR', 'QAR'), ('Pound', 'Pound'), ('USD', 'USD'), ('EUR', 'EURO')], default='QAR', max_length=20, null=True),
        ),
    ]
