# Generated by Django 4.2 on 2024-11-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundVideo',
        ),
        migrations.DeleteModel(
            name='CardOne',
        ),
        migrations.DeleteModel(
            name='CardTwo',
        ),
    ]
